[package]
name = "boardswarm-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.3.0"
futures = "0.3.25"
prost = "0.12"
prost-types = "0.12"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.23.0", features = ["full"] }
tonic = "0.10"

[build-dependencies]
prost-build = "0.12.0"
prost-wkt-build = "0.5.0"
tonic-build = "0.10"

[dev-dependencies]
serde_json = "1.0.91"
