name: test suite
on:
  push:
    branches-ignore:
      - "gh-readonly-queue/**"
  pull_request:
  merge_group:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Install build-depends
        run: sudo apt install -y protobuf-compiler libudev-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.70.0
      - run: cargo test --all-targets --all-features

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install build-depends
        run: sudo apt install -y protobuf-compiler libudev-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: clippy
      - run: cargo clippy --all-targets -- -D warnings

  minimal-dependencies:
    name: minimal direct dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install build-depends
        run: sudo apt install -y protobuf-compiler libudev-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: cargo check -Z direct-minimal-versions

  release builds:
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
    name: Release builds
    runs-on: ubuntu-latest
    container:
      image: rust:bookworm
    steps:
      - uses: actions/checkout@v4
      - name: Add ${matrix.arch} architecture
        run: dpkg --add-architecture ${{matrix.arch}}
      - name: Install build-depends
        run:
          apt update && apt install -y
            protobuf-compiler
            libudev-dev:${{matrix.arch}}
            libssl-dev:${{matrix.arch}}
      - name: target rust arch support
        run:
          rustup target add aarch64-unknown-linux-gnu
      - name: Setup arm64 environment
        if: ${{ matrix.arch == "arm64" }}
        run: |
          apt install -y gcc-aarch64-linux-gnu
          cat << EOF >> "$GITHUB_ENV"
            PKG_CONFIG_PATH_aarch64_unknown_linux_gnu=/usr/lib/aarch64-linux-gnu/pkgconfig
            PKG_CONFIG_ALLOW_CROSS=1
            CARGO_BUILD_TARGET=aarch64-unknown-linux-gnu
            CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          EOF
      - name: build
        run: cargo build --release

  allgreen:
    if: always()
    needs:
      - test
      - fmt
      - clippy
      - minimal-dependencies
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
